name: GitHub-Profile-3D-Contrib

on:
  schedule:
    - cron: "0 18 * * *" # 18:00 UTC = 01:00 VN
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate 3D Contributions
        uses: yoshi389111/github-profile-3d-contrib@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}

      - name: Commit & Push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions@users.noreply.github.com"

          if [[ -n $(git status --porcelain) ]]; then
            git add .
            git commit -m "chore: update 3d contribution graph"
            git push
          else
            echo "No changes"
          fi
